- name: check files to remove from temp folder
  win_find:
    paths: "{{ temp_folder }}"
    file_type: "{{ item }}"
    patterns: "*-SERVER-*"
  with_items:
    - file
    - directory
  register: cleanup_files

- name: remove files from temp folder
  win_file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ cleanup_files.results[0].files }}"
    - "{{ cleanup_files.results[1].files }}"
