
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - service_name
  - installation_root_folder
  - installation_folder
  - temp_folder

- name: stop the old service
  win_nssm:
    name: "{{ service_name }}"
    state: absent
  become: yes

# uninstall hasp - sentinel remove
- name: remove hasp installation
  win_command: '"{{ installation_folder }}\\bin\\haspdinst.exe" -r -fr -criticalmsg'
  become: yes
  ignore_errors: yes

- name: remove tracking files
  win_file: 
    path: "{{ installation_root_folder }}\\{{ item }}"
    state: absent
  with_items:
    - "{{ app_name }}-previous"
    - "{{ app_name }}-current"

- name: find app versions
  win_shell: |
    Get-ChildItem -Path {{ installation_root_folder }}\{{ app_name }}-* -Directory -Name
  register: application_versions
  changed_when: no

- name: remove application version
  block:

    - name: remove application versions - first attempt
      win_file:
        path: "{{ installation_root_folder }}\\{{ item }}"
        state: absent
      with_items: "{{ application_versions.stdout_lines }}"
      when: 
        - item | regex_search("{{ app_name }}-")
      register: remove_appver_first_try
      ignore_errors: yes

    - name: pause for 20 seconds if first attempt failed
      pause:
        seconds: 20
      when: remove_appver_first_try is failed

    - name: remove application versions - second attempt
      win_file:
        path: "{{ installation_root_folder }}\\{{ item }}"
        state: absent
      with_items: "{{ application_versions.stdout_lines }}"
      when: 
        - item | regex_search("{{ app_name }}-")
        - remove_appver_first_try is failed
      ignore_errors: yes
