
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - service_name
  - installation_folder
  - temp_folder

- name: stop the old service
  win_nssm:
    name: "{{ service_name }}"
    state: absent
  become: yes

# uninstall hasp
- name: remove hasp installation
  win_command: '"{{ installation_folder }}\\bin\\haspdinst.exe" -r -fr -criticalmsg'
  become: yes

- name: remove installation folder
  win_file: 
    path: "{{ installation_folder }}"
    state: absent

- name: remove temp folder
  win_file:
    path: "{{ temp_folder }}"
    state: absent
  when: clear_temp_folder | default('no') | bool
